[package]
name = "shibui-vocab-data"
description = "Shibui dictionary vocabulary fetcher"
version = "0.1.0"
authors = ["Do Tran", "quackablequackquack@gmail.com"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.5"
anyhow = "1.0.86"
